# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: websockets
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:client
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGODB_URI
        sync: false
